/*
Cloudsmith API (v1)

The API to the Cloudsmith Service

API version: 1.999.3
Contact: support@cloudsmith.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudsmith

import (
	"encoding/json"
	"fmt"
)

// checks if the BroadcastTokenInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BroadcastTokenInput{}

// BroadcastTokenInput struct for BroadcastTokenInput
type BroadcastTokenInput struct {
	// Repository entitlement token used to authorize the creation of a broadcast token
	EntitlementToken string `json:"entitlement_token"`
	// Token expiry time in seconds (optional, defaults to 3600 seconds)
	ExpiresIn            *int64 `json:"expires_in,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _BroadcastTokenInput BroadcastTokenInput

// NewBroadcastTokenInput instantiates a new BroadcastTokenInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBroadcastTokenInput(entitlementToken string) *BroadcastTokenInput {
	this := BroadcastTokenInput{}
	this.EntitlementToken = entitlementToken
	return &this
}

// NewBroadcastTokenInputWithDefaults instantiates a new BroadcastTokenInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBroadcastTokenInputWithDefaults() *BroadcastTokenInput {
	this := BroadcastTokenInput{}
	return &this
}

// GetEntitlementToken returns the EntitlementToken field value
func (o *BroadcastTokenInput) GetEntitlementToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EntitlementToken
}

// GetEntitlementTokenOk returns a tuple with the EntitlementToken field value
// and a boolean to check if the value has been set.
func (o *BroadcastTokenInput) GetEntitlementTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EntitlementToken, true
}

// SetEntitlementToken sets field value
func (o *BroadcastTokenInput) SetEntitlementToken(v string) {
	o.EntitlementToken = v
}

// GetExpiresIn returns the ExpiresIn field value if set, zero value otherwise.
func (o *BroadcastTokenInput) GetExpiresIn() int64 {
	if o == nil || IsNil(o.ExpiresIn) {
		var ret int64
		return ret
	}
	return *o.ExpiresIn
}

// GetExpiresInOk returns a tuple with the ExpiresIn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BroadcastTokenInput) GetExpiresInOk() (*int64, bool) {
	if o == nil || IsNil(o.ExpiresIn) {
		return nil, false
	}
	return o.ExpiresIn, true
}

// HasExpiresIn returns a boolean if a field has been set.
func (o *BroadcastTokenInput) HasExpiresIn() bool {
	if o != nil && !IsNil(o.ExpiresIn) {
		return true
	}

	return false
}

// SetExpiresIn gets a reference to the given int64 and assigns it to the ExpiresIn field.
func (o *BroadcastTokenInput) SetExpiresIn(v int64) {
	o.ExpiresIn = &v
}

func (o BroadcastTokenInput) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BroadcastTokenInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["entitlement_token"] = o.EntitlementToken
	if !IsNil(o.ExpiresIn) {
		toSerialize["expires_in"] = o.ExpiresIn
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BroadcastTokenInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"entitlement_token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBroadcastTokenInput := _BroadcastTokenInput{}

	err = json.Unmarshal(data, &varBroadcastTokenInput)

	if err != nil {
		return err
	}

	*o = BroadcastTokenInput(varBroadcastTokenInput)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "entitlement_token")
		delete(additionalProperties, "expires_in")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBroadcastTokenInput struct {
	value *BroadcastTokenInput
	isSet bool
}

func (v NullableBroadcastTokenInput) Get() *BroadcastTokenInput {
	return v.value
}

func (v *NullableBroadcastTokenInput) Set(val *BroadcastTokenInput) {
	v.value = val
	v.isSet = true
}

func (v NullableBroadcastTokenInput) IsSet() bool {
	return v.isSet
}

func (v *NullableBroadcastTokenInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBroadcastTokenInput(val *BroadcastTokenInput) *NullableBroadcastTokenInput {
	return &NullableBroadcastTokenInput{value: val, isSet: true}
}

func (v NullableBroadcastTokenInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBroadcastTokenInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
