/*
Cloudsmith API (v1)

The API to the Cloudsmith Service

API version: 1.181.6
Contact: support@cloudsmith.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudsmith

import (
	"encoding/json"
)

// EntitlementUsageMetricsResponse struct for EntitlementUsageMetricsResponse
type EntitlementUsageMetricsResponse struct {
	Tokens CommonMetrics `json:"tokens"`
}

// NewEntitlementUsageMetricsResponse instantiates a new EntitlementUsageMetricsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEntitlementUsageMetricsResponse(tokens CommonMetrics) *EntitlementUsageMetricsResponse {
	this := EntitlementUsageMetricsResponse{}
	this.Tokens = tokens
	return &this
}

// NewEntitlementUsageMetricsResponseWithDefaults instantiates a new EntitlementUsageMetricsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEntitlementUsageMetricsResponseWithDefaults() *EntitlementUsageMetricsResponse {
	this := EntitlementUsageMetricsResponse{}
	return &this
}

// GetTokens returns the Tokens field value
func (o *EntitlementUsageMetricsResponse) GetTokens() CommonMetrics {
	if o == nil {
		var ret CommonMetrics
		return ret
	}

	return o.Tokens
}

// GetTokensOk returns a tuple with the Tokens field value
// and a boolean to check if the value has been set.
func (o *EntitlementUsageMetricsResponse) GetTokensOk() (*CommonMetrics, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tokens, true
}

// SetTokens sets field value
func (o *EntitlementUsageMetricsResponse) SetTokens(v CommonMetrics) {
	o.Tokens = v
}

func (o EntitlementUsageMetricsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["tokens"] = o.Tokens
	}
	return json.Marshal(toSerialize)
}

type NullableEntitlementUsageMetricsResponse struct {
	value *EntitlementUsageMetricsResponse
	isSet bool
}

func (v NullableEntitlementUsageMetricsResponse) Get() *EntitlementUsageMetricsResponse {
	return v.value
}

func (v *NullableEntitlementUsageMetricsResponse) Set(val *EntitlementUsageMetricsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableEntitlementUsageMetricsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableEntitlementUsageMetricsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEntitlementUsageMetricsResponse(val *EntitlementUsageMetricsResponse) *NullableEntitlementUsageMetricsResponse {
	return &NullableEntitlementUsageMetricsResponse{value: val, isSet: true}
}

func (v NullableEntitlementUsageMetricsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEntitlementUsageMetricsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
