/*
Cloudsmith API (v1)

The API to the Cloudsmith Service

API version: 1.181.6
Contact: support@cloudsmith.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudsmith

import (
	"encoding/json"
	"time"
)

// TerraformPackageUploadResponse struct for TerraformPackageUploadResponse
type TerraformPackageUploadResponse struct {
	Architectures  []Architecture `json:"architectures,omitempty"`
	CdnUrl         NullableString `json:"cdn_url,omitempty"`
	ChecksumMd5    *string        `json:"checksum_md5,omitempty"`
	ChecksumSha1   *string        `json:"checksum_sha1,omitempty"`
	ChecksumSha256 *string        `json:"checksum_sha256,omitempty"`
	ChecksumSha512 *string        `json:"checksum_sha512,omitempty"`
	// A checksum of all of the package's dependencies.
	DependenciesChecksumMd5 *string `json:"dependencies_checksum_md5,omitempty"`
	DependenciesUrl         *string `json:"dependencies_url,omitempty"`
	// A textual description of this package.
	Description   *string              `json:"description,omitempty"`
	Distro        NullableDistribution `json:"distro,omitempty"`
	DistroVersion *DistributionVersion `json:"distro_version,omitempty"`
	Downloads     *int64               `json:"downloads,omitempty"`
	// The epoch of the package version (if any).
	Epoch     *int64        `json:"epoch,omitempty"`
	Extension *string       `json:"extension,omitempty"`
	Filename  *string       `json:"filename,omitempty"`
	Files     []PackageFile `json:"files,omitempty"`
	Format    *string       `json:"format,omitempty"`
	FormatUrl *string       `json:"format_url,omitempty"`
	// Unique and permanent identifier for the package.
	IdentifierPerm   *string `json:"identifier_perm,omitempty"`
	Indexed          *bool   `json:"indexed,omitempty"`
	IsDownloadable   *bool   `json:"is_downloadable,omitempty"`
	IsQuarantined    *bool   `json:"is_quarantined,omitempty"`
	IsSyncAwaiting   *bool   `json:"is_sync_awaiting,omitempty"`
	IsSyncCompleted  *bool   `json:"is_sync_completed,omitempty"`
	IsSyncFailed     *bool   `json:"is_sync_failed,omitempty"`
	IsSyncInFlight   *bool   `json:"is_sync_in_flight,omitempty"`
	IsSyncInProgress *bool   `json:"is_sync_in_progress,omitempty"`
	// The license of this package.
	License *string `json:"license,omitempty"`
	// The name of this package.
	Name                *string `json:"name,omitempty"`
	Namespace           *string `json:"namespace,omitempty"`
	NamespaceUrl        *string `json:"namespace_url,omitempty"`
	NumFiles            *int64  `json:"num_files,omitempty"`
	OriginRepository    *string `json:"origin_repository,omitempty"`
	OriginRepositoryUrl *string `json:"origin_repository_url,omitempty"`
	// The type of package contents.
	PackageType *int64 `json:"package_type,omitempty"`
	// The release of the package version (if any).
	Release       *string `json:"release,omitempty"`
	Repository    *string `json:"repository,omitempty"`
	RepositoryUrl *string `json:"repository_url,omitempty"`
	// The datetime the security scanning was completed.
	SecurityScanCompletedAt *time.Time `json:"security_scan_completed_at,omitempty"`
	// The datetime the security scanning was started.
	SecurityScanStartedAt *time.Time     `json:"security_scan_started_at,omitempty"`
	SecurityScanStatus    NullableString `json:"security_scan_status,omitempty"`
	// The datetime the security scanning status was updated.
	SecurityScanStatusUpdatedAt *time.Time     `json:"security_scan_status_updated_at,omitempty"`
	SelfHtmlUrl                 *string        `json:"self_html_url,omitempty"`
	SelfUrl                     *string        `json:"self_url,omitempty"`
	SignatureUrl                NullableString `json:"signature_url,omitempty"`
	// The calculated size of the package.
	Size *int64 `json:"size,omitempty"`
	// The public unique identifier for the package.
	Slug     *string `json:"slug,omitempty"`
	SlugPerm *string `json:"slug_perm,omitempty"`
	// The synchronisation (in progress) stage of the package.
	Stage    *int64  `json:"stage,omitempty"`
	StageStr *string `json:"stage_str,omitempty"`
	// The datetime the package stage was updated at.
	StageUpdatedAt *time.Time `json:"stage_updated_at,omitempty"`
	// The synchronisation status of the package.
	Status *int64 `json:"status,omitempty"`
	// A textual description for the synchronous status reason (if any
	StatusReason *string `json:"status_reason,omitempty"`
	StatusStr    *string `json:"status_str,omitempty"`
	// The datetime the package status was updated at.
	StatusUpdatedAt *time.Time `json:"status_updated_at,omitempty"`
	StatusUrl       *string    `json:"status_url,omitempty"`
	Subtype         *string    `json:"subtype,omitempty"`
	// A one-liner synopsis of this package.
	Summary *string `json:"summary,omitempty"`
	// The datetime the package sync was finished at.
	SyncFinishedAt *time.Time `json:"sync_finished_at,omitempty"`
	// Synchronisation progress (from 0-100)
	SyncProgress *int64 `json:"sync_progress,omitempty"`
	// All tags on the package, grouped by tag type. This includes immutable tags, but doesn't distinguish them from mutable. To see which tags are immutable specifically, see the tags_immutable field.
	TagsImmutable map[string]interface{} `json:"tags_immutable,omitempty"`
	TypeDisplay   *string                `json:"type_display,omitempty"`
	// The date this package was uploaded.
	UploadedAt  *time.Time `json:"uploaded_at,omitempty"`
	Uploader    *string    `json:"uploader,omitempty"`
	UploaderUrl *string    `json:"uploader_url,omitempty"`
	// The raw version for this package.
	Version                     *string `json:"version,omitempty"`
	VersionOrig                 *string `json:"version_orig,omitempty"`
	VulnerabilityScanResultsUrl *string `json:"vulnerability_scan_results_url,omitempty"`
}

// NewTerraformPackageUploadResponse instantiates a new TerraformPackageUploadResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTerraformPackageUploadResponse() *TerraformPackageUploadResponse {
	this := TerraformPackageUploadResponse{}
	return &this
}

// NewTerraformPackageUploadResponseWithDefaults instantiates a new TerraformPackageUploadResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTerraformPackageUploadResponseWithDefaults() *TerraformPackageUploadResponse {
	this := TerraformPackageUploadResponse{}
	return &this
}

// GetArchitectures returns the Architectures field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetArchitectures() []Architecture {
	if o == nil || isNil(o.Architectures) {
		var ret []Architecture
		return ret
	}
	return o.Architectures
}

// GetArchitecturesOk returns a tuple with the Architectures field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetArchitecturesOk() ([]Architecture, bool) {
	if o == nil || isNil(o.Architectures) {
		return nil, false
	}
	return o.Architectures, true
}

// HasArchitectures returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasArchitectures() bool {
	if o != nil && !isNil(o.Architectures) {
		return true
	}

	return false
}

// SetArchitectures gets a reference to the given []Architecture and assigns it to the Architectures field.
func (o *TerraformPackageUploadResponse) SetArchitectures(v []Architecture) {
	o.Architectures = v
}

// GetCdnUrl returns the CdnUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TerraformPackageUploadResponse) GetCdnUrl() string {
	if o == nil || isNil(o.CdnUrl.Get()) {
		var ret string
		return ret
	}
	return *o.CdnUrl.Get()
}

// GetCdnUrlOk returns a tuple with the CdnUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TerraformPackageUploadResponse) GetCdnUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CdnUrl.Get(), o.CdnUrl.IsSet()
}

// HasCdnUrl returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasCdnUrl() bool {
	if o != nil && o.CdnUrl.IsSet() {
		return true
	}

	return false
}

// SetCdnUrl gets a reference to the given NullableString and assigns it to the CdnUrl field.
func (o *TerraformPackageUploadResponse) SetCdnUrl(v string) {
	o.CdnUrl.Set(&v)
}

// SetCdnUrlNil sets the value for CdnUrl to be an explicit nil
func (o *TerraformPackageUploadResponse) SetCdnUrlNil() {
	o.CdnUrl.Set(nil)
}

// UnsetCdnUrl ensures that no value is present for CdnUrl, not even an explicit nil
func (o *TerraformPackageUploadResponse) UnsetCdnUrl() {
	o.CdnUrl.Unset()
}

// GetChecksumMd5 returns the ChecksumMd5 field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetChecksumMd5() string {
	if o == nil || isNil(o.ChecksumMd5) {
		var ret string
		return ret
	}
	return *o.ChecksumMd5
}

// GetChecksumMd5Ok returns a tuple with the ChecksumMd5 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetChecksumMd5Ok() (*string, bool) {
	if o == nil || isNil(o.ChecksumMd5) {
		return nil, false
	}
	return o.ChecksumMd5, true
}

// HasChecksumMd5 returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasChecksumMd5() bool {
	if o != nil && !isNil(o.ChecksumMd5) {
		return true
	}

	return false
}

// SetChecksumMd5 gets a reference to the given string and assigns it to the ChecksumMd5 field.
func (o *TerraformPackageUploadResponse) SetChecksumMd5(v string) {
	o.ChecksumMd5 = &v
}

// GetChecksumSha1 returns the ChecksumSha1 field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetChecksumSha1() string {
	if o == nil || isNil(o.ChecksumSha1) {
		var ret string
		return ret
	}
	return *o.ChecksumSha1
}

// GetChecksumSha1Ok returns a tuple with the ChecksumSha1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetChecksumSha1Ok() (*string, bool) {
	if o == nil || isNil(o.ChecksumSha1) {
		return nil, false
	}
	return o.ChecksumSha1, true
}

// HasChecksumSha1 returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasChecksumSha1() bool {
	if o != nil && !isNil(o.ChecksumSha1) {
		return true
	}

	return false
}

// SetChecksumSha1 gets a reference to the given string and assigns it to the ChecksumSha1 field.
func (o *TerraformPackageUploadResponse) SetChecksumSha1(v string) {
	o.ChecksumSha1 = &v
}

// GetChecksumSha256 returns the ChecksumSha256 field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetChecksumSha256() string {
	if o == nil || isNil(o.ChecksumSha256) {
		var ret string
		return ret
	}
	return *o.ChecksumSha256
}

// GetChecksumSha256Ok returns a tuple with the ChecksumSha256 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetChecksumSha256Ok() (*string, bool) {
	if o == nil || isNil(o.ChecksumSha256) {
		return nil, false
	}
	return o.ChecksumSha256, true
}

// HasChecksumSha256 returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasChecksumSha256() bool {
	if o != nil && !isNil(o.ChecksumSha256) {
		return true
	}

	return false
}

// SetChecksumSha256 gets a reference to the given string and assigns it to the ChecksumSha256 field.
func (o *TerraformPackageUploadResponse) SetChecksumSha256(v string) {
	o.ChecksumSha256 = &v
}

// GetChecksumSha512 returns the ChecksumSha512 field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetChecksumSha512() string {
	if o == nil || isNil(o.ChecksumSha512) {
		var ret string
		return ret
	}
	return *o.ChecksumSha512
}

// GetChecksumSha512Ok returns a tuple with the ChecksumSha512 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetChecksumSha512Ok() (*string, bool) {
	if o == nil || isNil(o.ChecksumSha512) {
		return nil, false
	}
	return o.ChecksumSha512, true
}

// HasChecksumSha512 returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasChecksumSha512() bool {
	if o != nil && !isNil(o.ChecksumSha512) {
		return true
	}

	return false
}

// SetChecksumSha512 gets a reference to the given string and assigns it to the ChecksumSha512 field.
func (o *TerraformPackageUploadResponse) SetChecksumSha512(v string) {
	o.ChecksumSha512 = &v
}

// GetDependenciesChecksumMd5 returns the DependenciesChecksumMd5 field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetDependenciesChecksumMd5() string {
	if o == nil || isNil(o.DependenciesChecksumMd5) {
		var ret string
		return ret
	}
	return *o.DependenciesChecksumMd5
}

// GetDependenciesChecksumMd5Ok returns a tuple with the DependenciesChecksumMd5 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetDependenciesChecksumMd5Ok() (*string, bool) {
	if o == nil || isNil(o.DependenciesChecksumMd5) {
		return nil, false
	}
	return o.DependenciesChecksumMd5, true
}

// HasDependenciesChecksumMd5 returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasDependenciesChecksumMd5() bool {
	if o != nil && !isNil(o.DependenciesChecksumMd5) {
		return true
	}

	return false
}

// SetDependenciesChecksumMd5 gets a reference to the given string and assigns it to the DependenciesChecksumMd5 field.
func (o *TerraformPackageUploadResponse) SetDependenciesChecksumMd5(v string) {
	o.DependenciesChecksumMd5 = &v
}

// GetDependenciesUrl returns the DependenciesUrl field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetDependenciesUrl() string {
	if o == nil || isNil(o.DependenciesUrl) {
		var ret string
		return ret
	}
	return *o.DependenciesUrl
}

// GetDependenciesUrlOk returns a tuple with the DependenciesUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetDependenciesUrlOk() (*string, bool) {
	if o == nil || isNil(o.DependenciesUrl) {
		return nil, false
	}
	return o.DependenciesUrl, true
}

// HasDependenciesUrl returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasDependenciesUrl() bool {
	if o != nil && !isNil(o.DependenciesUrl) {
		return true
	}

	return false
}

// SetDependenciesUrl gets a reference to the given string and assigns it to the DependenciesUrl field.
func (o *TerraformPackageUploadResponse) SetDependenciesUrl(v string) {
	o.DependenciesUrl = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetDescription() string {
	if o == nil || isNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetDescriptionOk() (*string, bool) {
	if o == nil || isNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasDescription() bool {
	if o != nil && !isNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *TerraformPackageUploadResponse) SetDescription(v string) {
	o.Description = &v
}

// GetDistro returns the Distro field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TerraformPackageUploadResponse) GetDistro() Distribution {
	if o == nil || isNil(o.Distro.Get()) {
		var ret Distribution
		return ret
	}
	return *o.Distro.Get()
}

// GetDistroOk returns a tuple with the Distro field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TerraformPackageUploadResponse) GetDistroOk() (*Distribution, bool) {
	if o == nil {
		return nil, false
	}
	return o.Distro.Get(), o.Distro.IsSet()
}

// HasDistro returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasDistro() bool {
	if o != nil && o.Distro.IsSet() {
		return true
	}

	return false
}

// SetDistro gets a reference to the given NullableDistribution and assigns it to the Distro field.
func (o *TerraformPackageUploadResponse) SetDistro(v Distribution) {
	o.Distro.Set(&v)
}

// SetDistroNil sets the value for Distro to be an explicit nil
func (o *TerraformPackageUploadResponse) SetDistroNil() {
	o.Distro.Set(nil)
}

// UnsetDistro ensures that no value is present for Distro, not even an explicit nil
func (o *TerraformPackageUploadResponse) UnsetDistro() {
	o.Distro.Unset()
}

// GetDistroVersion returns the DistroVersion field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetDistroVersion() DistributionVersion {
	if o == nil || isNil(o.DistroVersion) {
		var ret DistributionVersion
		return ret
	}
	return *o.DistroVersion
}

// GetDistroVersionOk returns a tuple with the DistroVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetDistroVersionOk() (*DistributionVersion, bool) {
	if o == nil || isNil(o.DistroVersion) {
		return nil, false
	}
	return o.DistroVersion, true
}

// HasDistroVersion returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasDistroVersion() bool {
	if o != nil && !isNil(o.DistroVersion) {
		return true
	}

	return false
}

// SetDistroVersion gets a reference to the given DistributionVersion and assigns it to the DistroVersion field.
func (o *TerraformPackageUploadResponse) SetDistroVersion(v DistributionVersion) {
	o.DistroVersion = &v
}

// GetDownloads returns the Downloads field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetDownloads() int64 {
	if o == nil || isNil(o.Downloads) {
		var ret int64
		return ret
	}
	return *o.Downloads
}

// GetDownloadsOk returns a tuple with the Downloads field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetDownloadsOk() (*int64, bool) {
	if o == nil || isNil(o.Downloads) {
		return nil, false
	}
	return o.Downloads, true
}

// HasDownloads returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasDownloads() bool {
	if o != nil && !isNil(o.Downloads) {
		return true
	}

	return false
}

// SetDownloads gets a reference to the given int64 and assigns it to the Downloads field.
func (o *TerraformPackageUploadResponse) SetDownloads(v int64) {
	o.Downloads = &v
}

// GetEpoch returns the Epoch field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetEpoch() int64 {
	if o == nil || isNil(o.Epoch) {
		var ret int64
		return ret
	}
	return *o.Epoch
}

// GetEpochOk returns a tuple with the Epoch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetEpochOk() (*int64, bool) {
	if o == nil || isNil(o.Epoch) {
		return nil, false
	}
	return o.Epoch, true
}

// HasEpoch returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasEpoch() bool {
	if o != nil && !isNil(o.Epoch) {
		return true
	}

	return false
}

// SetEpoch gets a reference to the given int64 and assigns it to the Epoch field.
func (o *TerraformPackageUploadResponse) SetEpoch(v int64) {
	o.Epoch = &v
}

// GetExtension returns the Extension field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetExtension() string {
	if o == nil || isNil(o.Extension) {
		var ret string
		return ret
	}
	return *o.Extension
}

// GetExtensionOk returns a tuple with the Extension field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetExtensionOk() (*string, bool) {
	if o == nil || isNil(o.Extension) {
		return nil, false
	}
	return o.Extension, true
}

// HasExtension returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasExtension() bool {
	if o != nil && !isNil(o.Extension) {
		return true
	}

	return false
}

// SetExtension gets a reference to the given string and assigns it to the Extension field.
func (o *TerraformPackageUploadResponse) SetExtension(v string) {
	o.Extension = &v
}

// GetFilename returns the Filename field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetFilename() string {
	if o == nil || isNil(o.Filename) {
		var ret string
		return ret
	}
	return *o.Filename
}

// GetFilenameOk returns a tuple with the Filename field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetFilenameOk() (*string, bool) {
	if o == nil || isNil(o.Filename) {
		return nil, false
	}
	return o.Filename, true
}

// HasFilename returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasFilename() bool {
	if o != nil && !isNil(o.Filename) {
		return true
	}

	return false
}

// SetFilename gets a reference to the given string and assigns it to the Filename field.
func (o *TerraformPackageUploadResponse) SetFilename(v string) {
	o.Filename = &v
}

// GetFiles returns the Files field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetFiles() []PackageFile {
	if o == nil || isNil(o.Files) {
		var ret []PackageFile
		return ret
	}
	return o.Files
}

// GetFilesOk returns a tuple with the Files field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetFilesOk() ([]PackageFile, bool) {
	if o == nil || isNil(o.Files) {
		return nil, false
	}
	return o.Files, true
}

// HasFiles returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasFiles() bool {
	if o != nil && !isNil(o.Files) {
		return true
	}

	return false
}

// SetFiles gets a reference to the given []PackageFile and assigns it to the Files field.
func (o *TerraformPackageUploadResponse) SetFiles(v []PackageFile) {
	o.Files = v
}

// GetFormat returns the Format field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetFormat() string {
	if o == nil || isNil(o.Format) {
		var ret string
		return ret
	}
	return *o.Format
}

// GetFormatOk returns a tuple with the Format field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetFormatOk() (*string, bool) {
	if o == nil || isNil(o.Format) {
		return nil, false
	}
	return o.Format, true
}

// HasFormat returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasFormat() bool {
	if o != nil && !isNil(o.Format) {
		return true
	}

	return false
}

// SetFormat gets a reference to the given string and assigns it to the Format field.
func (o *TerraformPackageUploadResponse) SetFormat(v string) {
	o.Format = &v
}

// GetFormatUrl returns the FormatUrl field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetFormatUrl() string {
	if o == nil || isNil(o.FormatUrl) {
		var ret string
		return ret
	}
	return *o.FormatUrl
}

// GetFormatUrlOk returns a tuple with the FormatUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetFormatUrlOk() (*string, bool) {
	if o == nil || isNil(o.FormatUrl) {
		return nil, false
	}
	return o.FormatUrl, true
}

// HasFormatUrl returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasFormatUrl() bool {
	if o != nil && !isNil(o.FormatUrl) {
		return true
	}

	return false
}

// SetFormatUrl gets a reference to the given string and assigns it to the FormatUrl field.
func (o *TerraformPackageUploadResponse) SetFormatUrl(v string) {
	o.FormatUrl = &v
}

// GetIdentifierPerm returns the IdentifierPerm field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetIdentifierPerm() string {
	if o == nil || isNil(o.IdentifierPerm) {
		var ret string
		return ret
	}
	return *o.IdentifierPerm
}

// GetIdentifierPermOk returns a tuple with the IdentifierPerm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetIdentifierPermOk() (*string, bool) {
	if o == nil || isNil(o.IdentifierPerm) {
		return nil, false
	}
	return o.IdentifierPerm, true
}

// HasIdentifierPerm returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasIdentifierPerm() bool {
	if o != nil && !isNil(o.IdentifierPerm) {
		return true
	}

	return false
}

// SetIdentifierPerm gets a reference to the given string and assigns it to the IdentifierPerm field.
func (o *TerraformPackageUploadResponse) SetIdentifierPerm(v string) {
	o.IdentifierPerm = &v
}

// GetIndexed returns the Indexed field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetIndexed() bool {
	if o == nil || isNil(o.Indexed) {
		var ret bool
		return ret
	}
	return *o.Indexed
}

// GetIndexedOk returns a tuple with the Indexed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetIndexedOk() (*bool, bool) {
	if o == nil || isNil(o.Indexed) {
		return nil, false
	}
	return o.Indexed, true
}

// HasIndexed returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasIndexed() bool {
	if o != nil && !isNil(o.Indexed) {
		return true
	}

	return false
}

// SetIndexed gets a reference to the given bool and assigns it to the Indexed field.
func (o *TerraformPackageUploadResponse) SetIndexed(v bool) {
	o.Indexed = &v
}

// GetIsDownloadable returns the IsDownloadable field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetIsDownloadable() bool {
	if o == nil || isNil(o.IsDownloadable) {
		var ret bool
		return ret
	}
	return *o.IsDownloadable
}

// GetIsDownloadableOk returns a tuple with the IsDownloadable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetIsDownloadableOk() (*bool, bool) {
	if o == nil || isNil(o.IsDownloadable) {
		return nil, false
	}
	return o.IsDownloadable, true
}

// HasIsDownloadable returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasIsDownloadable() bool {
	if o != nil && !isNil(o.IsDownloadable) {
		return true
	}

	return false
}

// SetIsDownloadable gets a reference to the given bool and assigns it to the IsDownloadable field.
func (o *TerraformPackageUploadResponse) SetIsDownloadable(v bool) {
	o.IsDownloadable = &v
}

// GetIsQuarantined returns the IsQuarantined field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetIsQuarantined() bool {
	if o == nil || isNil(o.IsQuarantined) {
		var ret bool
		return ret
	}
	return *o.IsQuarantined
}

// GetIsQuarantinedOk returns a tuple with the IsQuarantined field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetIsQuarantinedOk() (*bool, bool) {
	if o == nil || isNil(o.IsQuarantined) {
		return nil, false
	}
	return o.IsQuarantined, true
}

// HasIsQuarantined returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasIsQuarantined() bool {
	if o != nil && !isNil(o.IsQuarantined) {
		return true
	}

	return false
}

// SetIsQuarantined gets a reference to the given bool and assigns it to the IsQuarantined field.
func (o *TerraformPackageUploadResponse) SetIsQuarantined(v bool) {
	o.IsQuarantined = &v
}

// GetIsSyncAwaiting returns the IsSyncAwaiting field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetIsSyncAwaiting() bool {
	if o == nil || isNil(o.IsSyncAwaiting) {
		var ret bool
		return ret
	}
	return *o.IsSyncAwaiting
}

// GetIsSyncAwaitingOk returns a tuple with the IsSyncAwaiting field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetIsSyncAwaitingOk() (*bool, bool) {
	if o == nil || isNil(o.IsSyncAwaiting) {
		return nil, false
	}
	return o.IsSyncAwaiting, true
}

// HasIsSyncAwaiting returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasIsSyncAwaiting() bool {
	if o != nil && !isNil(o.IsSyncAwaiting) {
		return true
	}

	return false
}

// SetIsSyncAwaiting gets a reference to the given bool and assigns it to the IsSyncAwaiting field.
func (o *TerraformPackageUploadResponse) SetIsSyncAwaiting(v bool) {
	o.IsSyncAwaiting = &v
}

// GetIsSyncCompleted returns the IsSyncCompleted field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetIsSyncCompleted() bool {
	if o == nil || isNil(o.IsSyncCompleted) {
		var ret bool
		return ret
	}
	return *o.IsSyncCompleted
}

// GetIsSyncCompletedOk returns a tuple with the IsSyncCompleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetIsSyncCompletedOk() (*bool, bool) {
	if o == nil || isNil(o.IsSyncCompleted) {
		return nil, false
	}
	return o.IsSyncCompleted, true
}

// HasIsSyncCompleted returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasIsSyncCompleted() bool {
	if o != nil && !isNil(o.IsSyncCompleted) {
		return true
	}

	return false
}

// SetIsSyncCompleted gets a reference to the given bool and assigns it to the IsSyncCompleted field.
func (o *TerraformPackageUploadResponse) SetIsSyncCompleted(v bool) {
	o.IsSyncCompleted = &v
}

// GetIsSyncFailed returns the IsSyncFailed field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetIsSyncFailed() bool {
	if o == nil || isNil(o.IsSyncFailed) {
		var ret bool
		return ret
	}
	return *o.IsSyncFailed
}

// GetIsSyncFailedOk returns a tuple with the IsSyncFailed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetIsSyncFailedOk() (*bool, bool) {
	if o == nil || isNil(o.IsSyncFailed) {
		return nil, false
	}
	return o.IsSyncFailed, true
}

// HasIsSyncFailed returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasIsSyncFailed() bool {
	if o != nil && !isNil(o.IsSyncFailed) {
		return true
	}

	return false
}

// SetIsSyncFailed gets a reference to the given bool and assigns it to the IsSyncFailed field.
func (o *TerraformPackageUploadResponse) SetIsSyncFailed(v bool) {
	o.IsSyncFailed = &v
}

// GetIsSyncInFlight returns the IsSyncInFlight field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetIsSyncInFlight() bool {
	if o == nil || isNil(o.IsSyncInFlight) {
		var ret bool
		return ret
	}
	return *o.IsSyncInFlight
}

// GetIsSyncInFlightOk returns a tuple with the IsSyncInFlight field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetIsSyncInFlightOk() (*bool, bool) {
	if o == nil || isNil(o.IsSyncInFlight) {
		return nil, false
	}
	return o.IsSyncInFlight, true
}

// HasIsSyncInFlight returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasIsSyncInFlight() bool {
	if o != nil && !isNil(o.IsSyncInFlight) {
		return true
	}

	return false
}

// SetIsSyncInFlight gets a reference to the given bool and assigns it to the IsSyncInFlight field.
func (o *TerraformPackageUploadResponse) SetIsSyncInFlight(v bool) {
	o.IsSyncInFlight = &v
}

// GetIsSyncInProgress returns the IsSyncInProgress field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetIsSyncInProgress() bool {
	if o == nil || isNil(o.IsSyncInProgress) {
		var ret bool
		return ret
	}
	return *o.IsSyncInProgress
}

// GetIsSyncInProgressOk returns a tuple with the IsSyncInProgress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetIsSyncInProgressOk() (*bool, bool) {
	if o == nil || isNil(o.IsSyncInProgress) {
		return nil, false
	}
	return o.IsSyncInProgress, true
}

// HasIsSyncInProgress returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasIsSyncInProgress() bool {
	if o != nil && !isNil(o.IsSyncInProgress) {
		return true
	}

	return false
}

// SetIsSyncInProgress gets a reference to the given bool and assigns it to the IsSyncInProgress field.
func (o *TerraformPackageUploadResponse) SetIsSyncInProgress(v bool) {
	o.IsSyncInProgress = &v
}

// GetLicense returns the License field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetLicense() string {
	if o == nil || isNil(o.License) {
		var ret string
		return ret
	}
	return *o.License
}

// GetLicenseOk returns a tuple with the License field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetLicenseOk() (*string, bool) {
	if o == nil || isNil(o.License) {
		return nil, false
	}
	return o.License, true
}

// HasLicense returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasLicense() bool {
	if o != nil && !isNil(o.License) {
		return true
	}

	return false
}

// SetLicense gets a reference to the given string and assigns it to the License field.
func (o *TerraformPackageUploadResponse) SetLicense(v string) {
	o.License = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetName() string {
	if o == nil || isNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetNameOk() (*string, bool) {
	if o == nil || isNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasName() bool {
	if o != nil && !isNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *TerraformPackageUploadResponse) SetName(v string) {
	o.Name = &v
}

// GetNamespace returns the Namespace field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetNamespace() string {
	if o == nil || isNil(o.Namespace) {
		var ret string
		return ret
	}
	return *o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetNamespaceOk() (*string, bool) {
	if o == nil || isNil(o.Namespace) {
		return nil, false
	}
	return o.Namespace, true
}

// HasNamespace returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasNamespace() bool {
	if o != nil && !isNil(o.Namespace) {
		return true
	}

	return false
}

// SetNamespace gets a reference to the given string and assigns it to the Namespace field.
func (o *TerraformPackageUploadResponse) SetNamespace(v string) {
	o.Namespace = &v
}

// GetNamespaceUrl returns the NamespaceUrl field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetNamespaceUrl() string {
	if o == nil || isNil(o.NamespaceUrl) {
		var ret string
		return ret
	}
	return *o.NamespaceUrl
}

// GetNamespaceUrlOk returns a tuple with the NamespaceUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetNamespaceUrlOk() (*string, bool) {
	if o == nil || isNil(o.NamespaceUrl) {
		return nil, false
	}
	return o.NamespaceUrl, true
}

// HasNamespaceUrl returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasNamespaceUrl() bool {
	if o != nil && !isNil(o.NamespaceUrl) {
		return true
	}

	return false
}

// SetNamespaceUrl gets a reference to the given string and assigns it to the NamespaceUrl field.
func (o *TerraformPackageUploadResponse) SetNamespaceUrl(v string) {
	o.NamespaceUrl = &v
}

// GetNumFiles returns the NumFiles field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetNumFiles() int64 {
	if o == nil || isNil(o.NumFiles) {
		var ret int64
		return ret
	}
	return *o.NumFiles
}

// GetNumFilesOk returns a tuple with the NumFiles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetNumFilesOk() (*int64, bool) {
	if o == nil || isNil(o.NumFiles) {
		return nil, false
	}
	return o.NumFiles, true
}

// HasNumFiles returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasNumFiles() bool {
	if o != nil && !isNil(o.NumFiles) {
		return true
	}

	return false
}

// SetNumFiles gets a reference to the given int64 and assigns it to the NumFiles field.
func (o *TerraformPackageUploadResponse) SetNumFiles(v int64) {
	o.NumFiles = &v
}

// GetOriginRepository returns the OriginRepository field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetOriginRepository() string {
	if o == nil || isNil(o.OriginRepository) {
		var ret string
		return ret
	}
	return *o.OriginRepository
}

// GetOriginRepositoryOk returns a tuple with the OriginRepository field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetOriginRepositoryOk() (*string, bool) {
	if o == nil || isNil(o.OriginRepository) {
		return nil, false
	}
	return o.OriginRepository, true
}

// HasOriginRepository returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasOriginRepository() bool {
	if o != nil && !isNil(o.OriginRepository) {
		return true
	}

	return false
}

// SetOriginRepository gets a reference to the given string and assigns it to the OriginRepository field.
func (o *TerraformPackageUploadResponse) SetOriginRepository(v string) {
	o.OriginRepository = &v
}

// GetOriginRepositoryUrl returns the OriginRepositoryUrl field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetOriginRepositoryUrl() string {
	if o == nil || isNil(o.OriginRepositoryUrl) {
		var ret string
		return ret
	}
	return *o.OriginRepositoryUrl
}

// GetOriginRepositoryUrlOk returns a tuple with the OriginRepositoryUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetOriginRepositoryUrlOk() (*string, bool) {
	if o == nil || isNil(o.OriginRepositoryUrl) {
		return nil, false
	}
	return o.OriginRepositoryUrl, true
}

// HasOriginRepositoryUrl returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasOriginRepositoryUrl() bool {
	if o != nil && !isNil(o.OriginRepositoryUrl) {
		return true
	}

	return false
}

// SetOriginRepositoryUrl gets a reference to the given string and assigns it to the OriginRepositoryUrl field.
func (o *TerraformPackageUploadResponse) SetOriginRepositoryUrl(v string) {
	o.OriginRepositoryUrl = &v
}

// GetPackageType returns the PackageType field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetPackageType() int64 {
	if o == nil || isNil(o.PackageType) {
		var ret int64
		return ret
	}
	return *o.PackageType
}

// GetPackageTypeOk returns a tuple with the PackageType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetPackageTypeOk() (*int64, bool) {
	if o == nil || isNil(o.PackageType) {
		return nil, false
	}
	return o.PackageType, true
}

// HasPackageType returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasPackageType() bool {
	if o != nil && !isNil(o.PackageType) {
		return true
	}

	return false
}

// SetPackageType gets a reference to the given int64 and assigns it to the PackageType field.
func (o *TerraformPackageUploadResponse) SetPackageType(v int64) {
	o.PackageType = &v
}

// GetRelease returns the Release field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetRelease() string {
	if o == nil || isNil(o.Release) {
		var ret string
		return ret
	}
	return *o.Release
}

// GetReleaseOk returns a tuple with the Release field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetReleaseOk() (*string, bool) {
	if o == nil || isNil(o.Release) {
		return nil, false
	}
	return o.Release, true
}

// HasRelease returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasRelease() bool {
	if o != nil && !isNil(o.Release) {
		return true
	}

	return false
}

// SetRelease gets a reference to the given string and assigns it to the Release field.
func (o *TerraformPackageUploadResponse) SetRelease(v string) {
	o.Release = &v
}

// GetRepository returns the Repository field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetRepository() string {
	if o == nil || isNil(o.Repository) {
		var ret string
		return ret
	}
	return *o.Repository
}

// GetRepositoryOk returns a tuple with the Repository field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetRepositoryOk() (*string, bool) {
	if o == nil || isNil(o.Repository) {
		return nil, false
	}
	return o.Repository, true
}

// HasRepository returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasRepository() bool {
	if o != nil && !isNil(o.Repository) {
		return true
	}

	return false
}

// SetRepository gets a reference to the given string and assigns it to the Repository field.
func (o *TerraformPackageUploadResponse) SetRepository(v string) {
	o.Repository = &v
}

// GetRepositoryUrl returns the RepositoryUrl field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetRepositoryUrl() string {
	if o == nil || isNil(o.RepositoryUrl) {
		var ret string
		return ret
	}
	return *o.RepositoryUrl
}

// GetRepositoryUrlOk returns a tuple with the RepositoryUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetRepositoryUrlOk() (*string, bool) {
	if o == nil || isNil(o.RepositoryUrl) {
		return nil, false
	}
	return o.RepositoryUrl, true
}

// HasRepositoryUrl returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasRepositoryUrl() bool {
	if o != nil && !isNil(o.RepositoryUrl) {
		return true
	}

	return false
}

// SetRepositoryUrl gets a reference to the given string and assigns it to the RepositoryUrl field.
func (o *TerraformPackageUploadResponse) SetRepositoryUrl(v string) {
	o.RepositoryUrl = &v
}

// GetSecurityScanCompletedAt returns the SecurityScanCompletedAt field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetSecurityScanCompletedAt() time.Time {
	if o == nil || isNil(o.SecurityScanCompletedAt) {
		var ret time.Time
		return ret
	}
	return *o.SecurityScanCompletedAt
}

// GetSecurityScanCompletedAtOk returns a tuple with the SecurityScanCompletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetSecurityScanCompletedAtOk() (*time.Time, bool) {
	if o == nil || isNil(o.SecurityScanCompletedAt) {
		return nil, false
	}
	return o.SecurityScanCompletedAt, true
}

// HasSecurityScanCompletedAt returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasSecurityScanCompletedAt() bool {
	if o != nil && !isNil(o.SecurityScanCompletedAt) {
		return true
	}

	return false
}

// SetSecurityScanCompletedAt gets a reference to the given time.Time and assigns it to the SecurityScanCompletedAt field.
func (o *TerraformPackageUploadResponse) SetSecurityScanCompletedAt(v time.Time) {
	o.SecurityScanCompletedAt = &v
}

// GetSecurityScanStartedAt returns the SecurityScanStartedAt field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetSecurityScanStartedAt() time.Time {
	if o == nil || isNil(o.SecurityScanStartedAt) {
		var ret time.Time
		return ret
	}
	return *o.SecurityScanStartedAt
}

// GetSecurityScanStartedAtOk returns a tuple with the SecurityScanStartedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetSecurityScanStartedAtOk() (*time.Time, bool) {
	if o == nil || isNil(o.SecurityScanStartedAt) {
		return nil, false
	}
	return o.SecurityScanStartedAt, true
}

// HasSecurityScanStartedAt returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasSecurityScanStartedAt() bool {
	if o != nil && !isNil(o.SecurityScanStartedAt) {
		return true
	}

	return false
}

// SetSecurityScanStartedAt gets a reference to the given time.Time and assigns it to the SecurityScanStartedAt field.
func (o *TerraformPackageUploadResponse) SetSecurityScanStartedAt(v time.Time) {
	o.SecurityScanStartedAt = &v
}

// GetSecurityScanStatus returns the SecurityScanStatus field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TerraformPackageUploadResponse) GetSecurityScanStatus() string {
	if o == nil || isNil(o.SecurityScanStatus.Get()) {
		var ret string
		return ret
	}
	return *o.SecurityScanStatus.Get()
}

// GetSecurityScanStatusOk returns a tuple with the SecurityScanStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TerraformPackageUploadResponse) GetSecurityScanStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SecurityScanStatus.Get(), o.SecurityScanStatus.IsSet()
}

// HasSecurityScanStatus returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasSecurityScanStatus() bool {
	if o != nil && o.SecurityScanStatus.IsSet() {
		return true
	}

	return false
}

// SetSecurityScanStatus gets a reference to the given NullableString and assigns it to the SecurityScanStatus field.
func (o *TerraformPackageUploadResponse) SetSecurityScanStatus(v string) {
	o.SecurityScanStatus.Set(&v)
}

// SetSecurityScanStatusNil sets the value for SecurityScanStatus to be an explicit nil
func (o *TerraformPackageUploadResponse) SetSecurityScanStatusNil() {
	o.SecurityScanStatus.Set(nil)
}

// UnsetSecurityScanStatus ensures that no value is present for SecurityScanStatus, not even an explicit nil
func (o *TerraformPackageUploadResponse) UnsetSecurityScanStatus() {
	o.SecurityScanStatus.Unset()
}

// GetSecurityScanStatusUpdatedAt returns the SecurityScanStatusUpdatedAt field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetSecurityScanStatusUpdatedAt() time.Time {
	if o == nil || isNil(o.SecurityScanStatusUpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.SecurityScanStatusUpdatedAt
}

// GetSecurityScanStatusUpdatedAtOk returns a tuple with the SecurityScanStatusUpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetSecurityScanStatusUpdatedAtOk() (*time.Time, bool) {
	if o == nil || isNil(o.SecurityScanStatusUpdatedAt) {
		return nil, false
	}
	return o.SecurityScanStatusUpdatedAt, true
}

// HasSecurityScanStatusUpdatedAt returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasSecurityScanStatusUpdatedAt() bool {
	if o != nil && !isNil(o.SecurityScanStatusUpdatedAt) {
		return true
	}

	return false
}

// SetSecurityScanStatusUpdatedAt gets a reference to the given time.Time and assigns it to the SecurityScanStatusUpdatedAt field.
func (o *TerraformPackageUploadResponse) SetSecurityScanStatusUpdatedAt(v time.Time) {
	o.SecurityScanStatusUpdatedAt = &v
}

// GetSelfHtmlUrl returns the SelfHtmlUrl field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetSelfHtmlUrl() string {
	if o == nil || isNil(o.SelfHtmlUrl) {
		var ret string
		return ret
	}
	return *o.SelfHtmlUrl
}

// GetSelfHtmlUrlOk returns a tuple with the SelfHtmlUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetSelfHtmlUrlOk() (*string, bool) {
	if o == nil || isNil(o.SelfHtmlUrl) {
		return nil, false
	}
	return o.SelfHtmlUrl, true
}

// HasSelfHtmlUrl returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasSelfHtmlUrl() bool {
	if o != nil && !isNil(o.SelfHtmlUrl) {
		return true
	}

	return false
}

// SetSelfHtmlUrl gets a reference to the given string and assigns it to the SelfHtmlUrl field.
func (o *TerraformPackageUploadResponse) SetSelfHtmlUrl(v string) {
	o.SelfHtmlUrl = &v
}

// GetSelfUrl returns the SelfUrl field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetSelfUrl() string {
	if o == nil || isNil(o.SelfUrl) {
		var ret string
		return ret
	}
	return *o.SelfUrl
}

// GetSelfUrlOk returns a tuple with the SelfUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetSelfUrlOk() (*string, bool) {
	if o == nil || isNil(o.SelfUrl) {
		return nil, false
	}
	return o.SelfUrl, true
}

// HasSelfUrl returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasSelfUrl() bool {
	if o != nil && !isNil(o.SelfUrl) {
		return true
	}

	return false
}

// SetSelfUrl gets a reference to the given string and assigns it to the SelfUrl field.
func (o *TerraformPackageUploadResponse) SetSelfUrl(v string) {
	o.SelfUrl = &v
}

// GetSignatureUrl returns the SignatureUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TerraformPackageUploadResponse) GetSignatureUrl() string {
	if o == nil || isNil(o.SignatureUrl.Get()) {
		var ret string
		return ret
	}
	return *o.SignatureUrl.Get()
}

// GetSignatureUrlOk returns a tuple with the SignatureUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TerraformPackageUploadResponse) GetSignatureUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SignatureUrl.Get(), o.SignatureUrl.IsSet()
}

// HasSignatureUrl returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasSignatureUrl() bool {
	if o != nil && o.SignatureUrl.IsSet() {
		return true
	}

	return false
}

// SetSignatureUrl gets a reference to the given NullableString and assigns it to the SignatureUrl field.
func (o *TerraformPackageUploadResponse) SetSignatureUrl(v string) {
	o.SignatureUrl.Set(&v)
}

// SetSignatureUrlNil sets the value for SignatureUrl to be an explicit nil
func (o *TerraformPackageUploadResponse) SetSignatureUrlNil() {
	o.SignatureUrl.Set(nil)
}

// UnsetSignatureUrl ensures that no value is present for SignatureUrl, not even an explicit nil
func (o *TerraformPackageUploadResponse) UnsetSignatureUrl() {
	o.SignatureUrl.Unset()
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetSize() int64 {
	if o == nil || isNil(o.Size) {
		var ret int64
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetSizeOk() (*int64, bool) {
	if o == nil || isNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasSize() bool {
	if o != nil && !isNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given int64 and assigns it to the Size field.
func (o *TerraformPackageUploadResponse) SetSize(v int64) {
	o.Size = &v
}

// GetSlug returns the Slug field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetSlug() string {
	if o == nil || isNil(o.Slug) {
		var ret string
		return ret
	}
	return *o.Slug
}

// GetSlugOk returns a tuple with the Slug field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetSlugOk() (*string, bool) {
	if o == nil || isNil(o.Slug) {
		return nil, false
	}
	return o.Slug, true
}

// HasSlug returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasSlug() bool {
	if o != nil && !isNil(o.Slug) {
		return true
	}

	return false
}

// SetSlug gets a reference to the given string and assigns it to the Slug field.
func (o *TerraformPackageUploadResponse) SetSlug(v string) {
	o.Slug = &v
}

// GetSlugPerm returns the SlugPerm field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetSlugPerm() string {
	if o == nil || isNil(o.SlugPerm) {
		var ret string
		return ret
	}
	return *o.SlugPerm
}

// GetSlugPermOk returns a tuple with the SlugPerm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetSlugPermOk() (*string, bool) {
	if o == nil || isNil(o.SlugPerm) {
		return nil, false
	}
	return o.SlugPerm, true
}

// HasSlugPerm returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasSlugPerm() bool {
	if o != nil && !isNil(o.SlugPerm) {
		return true
	}

	return false
}

// SetSlugPerm gets a reference to the given string and assigns it to the SlugPerm field.
func (o *TerraformPackageUploadResponse) SetSlugPerm(v string) {
	o.SlugPerm = &v
}

// GetStage returns the Stage field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetStage() int64 {
	if o == nil || isNil(o.Stage) {
		var ret int64
		return ret
	}
	return *o.Stage
}

// GetStageOk returns a tuple with the Stage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetStageOk() (*int64, bool) {
	if o == nil || isNil(o.Stage) {
		return nil, false
	}
	return o.Stage, true
}

// HasStage returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasStage() bool {
	if o != nil && !isNil(o.Stage) {
		return true
	}

	return false
}

// SetStage gets a reference to the given int64 and assigns it to the Stage field.
func (o *TerraformPackageUploadResponse) SetStage(v int64) {
	o.Stage = &v
}

// GetStageStr returns the StageStr field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetStageStr() string {
	if o == nil || isNil(o.StageStr) {
		var ret string
		return ret
	}
	return *o.StageStr
}

// GetStageStrOk returns a tuple with the StageStr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetStageStrOk() (*string, bool) {
	if o == nil || isNil(o.StageStr) {
		return nil, false
	}
	return o.StageStr, true
}

// HasStageStr returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasStageStr() bool {
	if o != nil && !isNil(o.StageStr) {
		return true
	}

	return false
}

// SetStageStr gets a reference to the given string and assigns it to the StageStr field.
func (o *TerraformPackageUploadResponse) SetStageStr(v string) {
	o.StageStr = &v
}

// GetStageUpdatedAt returns the StageUpdatedAt field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetStageUpdatedAt() time.Time {
	if o == nil || isNil(o.StageUpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.StageUpdatedAt
}

// GetStageUpdatedAtOk returns a tuple with the StageUpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetStageUpdatedAtOk() (*time.Time, bool) {
	if o == nil || isNil(o.StageUpdatedAt) {
		return nil, false
	}
	return o.StageUpdatedAt, true
}

// HasStageUpdatedAt returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasStageUpdatedAt() bool {
	if o != nil && !isNil(o.StageUpdatedAt) {
		return true
	}

	return false
}

// SetStageUpdatedAt gets a reference to the given time.Time and assigns it to the StageUpdatedAt field.
func (o *TerraformPackageUploadResponse) SetStageUpdatedAt(v time.Time) {
	o.StageUpdatedAt = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetStatus() int64 {
	if o == nil || isNil(o.Status) {
		var ret int64
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetStatusOk() (*int64, bool) {
	if o == nil || isNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasStatus() bool {
	if o != nil && !isNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given int64 and assigns it to the Status field.
func (o *TerraformPackageUploadResponse) SetStatus(v int64) {
	o.Status = &v
}

// GetStatusReason returns the StatusReason field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetStatusReason() string {
	if o == nil || isNil(o.StatusReason) {
		var ret string
		return ret
	}
	return *o.StatusReason
}

// GetStatusReasonOk returns a tuple with the StatusReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetStatusReasonOk() (*string, bool) {
	if o == nil || isNil(o.StatusReason) {
		return nil, false
	}
	return o.StatusReason, true
}

// HasStatusReason returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasStatusReason() bool {
	if o != nil && !isNil(o.StatusReason) {
		return true
	}

	return false
}

// SetStatusReason gets a reference to the given string and assigns it to the StatusReason field.
func (o *TerraformPackageUploadResponse) SetStatusReason(v string) {
	o.StatusReason = &v
}

// GetStatusStr returns the StatusStr field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetStatusStr() string {
	if o == nil || isNil(o.StatusStr) {
		var ret string
		return ret
	}
	return *o.StatusStr
}

// GetStatusStrOk returns a tuple with the StatusStr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetStatusStrOk() (*string, bool) {
	if o == nil || isNil(o.StatusStr) {
		return nil, false
	}
	return o.StatusStr, true
}

// HasStatusStr returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasStatusStr() bool {
	if o != nil && !isNil(o.StatusStr) {
		return true
	}

	return false
}

// SetStatusStr gets a reference to the given string and assigns it to the StatusStr field.
func (o *TerraformPackageUploadResponse) SetStatusStr(v string) {
	o.StatusStr = &v
}

// GetStatusUpdatedAt returns the StatusUpdatedAt field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetStatusUpdatedAt() time.Time {
	if o == nil || isNil(o.StatusUpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.StatusUpdatedAt
}

// GetStatusUpdatedAtOk returns a tuple with the StatusUpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetStatusUpdatedAtOk() (*time.Time, bool) {
	if o == nil || isNil(o.StatusUpdatedAt) {
		return nil, false
	}
	return o.StatusUpdatedAt, true
}

// HasStatusUpdatedAt returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasStatusUpdatedAt() bool {
	if o != nil && !isNil(o.StatusUpdatedAt) {
		return true
	}

	return false
}

// SetStatusUpdatedAt gets a reference to the given time.Time and assigns it to the StatusUpdatedAt field.
func (o *TerraformPackageUploadResponse) SetStatusUpdatedAt(v time.Time) {
	o.StatusUpdatedAt = &v
}

// GetStatusUrl returns the StatusUrl field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetStatusUrl() string {
	if o == nil || isNil(o.StatusUrl) {
		var ret string
		return ret
	}
	return *o.StatusUrl
}

// GetStatusUrlOk returns a tuple with the StatusUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetStatusUrlOk() (*string, bool) {
	if o == nil || isNil(o.StatusUrl) {
		return nil, false
	}
	return o.StatusUrl, true
}

// HasStatusUrl returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasStatusUrl() bool {
	if o != nil && !isNil(o.StatusUrl) {
		return true
	}

	return false
}

// SetStatusUrl gets a reference to the given string and assigns it to the StatusUrl field.
func (o *TerraformPackageUploadResponse) SetStatusUrl(v string) {
	o.StatusUrl = &v
}

// GetSubtype returns the Subtype field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetSubtype() string {
	if o == nil || isNil(o.Subtype) {
		var ret string
		return ret
	}
	return *o.Subtype
}

// GetSubtypeOk returns a tuple with the Subtype field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetSubtypeOk() (*string, bool) {
	if o == nil || isNil(o.Subtype) {
		return nil, false
	}
	return o.Subtype, true
}

// HasSubtype returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasSubtype() bool {
	if o != nil && !isNil(o.Subtype) {
		return true
	}

	return false
}

// SetSubtype gets a reference to the given string and assigns it to the Subtype field.
func (o *TerraformPackageUploadResponse) SetSubtype(v string) {
	o.Subtype = &v
}

// GetSummary returns the Summary field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetSummary() string {
	if o == nil || isNil(o.Summary) {
		var ret string
		return ret
	}
	return *o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetSummaryOk() (*string, bool) {
	if o == nil || isNil(o.Summary) {
		return nil, false
	}
	return o.Summary, true
}

// HasSummary returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasSummary() bool {
	if o != nil && !isNil(o.Summary) {
		return true
	}

	return false
}

// SetSummary gets a reference to the given string and assigns it to the Summary field.
func (o *TerraformPackageUploadResponse) SetSummary(v string) {
	o.Summary = &v
}

// GetSyncFinishedAt returns the SyncFinishedAt field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetSyncFinishedAt() time.Time {
	if o == nil || isNil(o.SyncFinishedAt) {
		var ret time.Time
		return ret
	}
	return *o.SyncFinishedAt
}

// GetSyncFinishedAtOk returns a tuple with the SyncFinishedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetSyncFinishedAtOk() (*time.Time, bool) {
	if o == nil || isNil(o.SyncFinishedAt) {
		return nil, false
	}
	return o.SyncFinishedAt, true
}

// HasSyncFinishedAt returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasSyncFinishedAt() bool {
	if o != nil && !isNil(o.SyncFinishedAt) {
		return true
	}

	return false
}

// SetSyncFinishedAt gets a reference to the given time.Time and assigns it to the SyncFinishedAt field.
func (o *TerraformPackageUploadResponse) SetSyncFinishedAt(v time.Time) {
	o.SyncFinishedAt = &v
}

// GetSyncProgress returns the SyncProgress field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetSyncProgress() int64 {
	if o == nil || isNil(o.SyncProgress) {
		var ret int64
		return ret
	}
	return *o.SyncProgress
}

// GetSyncProgressOk returns a tuple with the SyncProgress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetSyncProgressOk() (*int64, bool) {
	if o == nil || isNil(o.SyncProgress) {
		return nil, false
	}
	return o.SyncProgress, true
}

// HasSyncProgress returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasSyncProgress() bool {
	if o != nil && !isNil(o.SyncProgress) {
		return true
	}

	return false
}

// SetSyncProgress gets a reference to the given int64 and assigns it to the SyncProgress field.
func (o *TerraformPackageUploadResponse) SetSyncProgress(v int64) {
	o.SyncProgress = &v
}

// GetTagsImmutable returns the TagsImmutable field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetTagsImmutable() map[string]interface{} {
	if o == nil || isNil(o.TagsImmutable) {
		var ret map[string]interface{}
		return ret
	}
	return o.TagsImmutable
}

// GetTagsImmutableOk returns a tuple with the TagsImmutable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetTagsImmutableOk() (map[string]interface{}, bool) {
	if o == nil || isNil(o.TagsImmutable) {
		return map[string]interface{}{}, false
	}
	return o.TagsImmutable, true
}

// HasTagsImmutable returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasTagsImmutable() bool {
	if o != nil && !isNil(o.TagsImmutable) {
		return true
	}

	return false
}

// SetTagsImmutable gets a reference to the given map[string]interface{} and assigns it to the TagsImmutable field.
func (o *TerraformPackageUploadResponse) SetTagsImmutable(v map[string]interface{}) {
	o.TagsImmutable = v
}

// GetTypeDisplay returns the TypeDisplay field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetTypeDisplay() string {
	if o == nil || isNil(o.TypeDisplay) {
		var ret string
		return ret
	}
	return *o.TypeDisplay
}

// GetTypeDisplayOk returns a tuple with the TypeDisplay field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetTypeDisplayOk() (*string, bool) {
	if o == nil || isNil(o.TypeDisplay) {
		return nil, false
	}
	return o.TypeDisplay, true
}

// HasTypeDisplay returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasTypeDisplay() bool {
	if o != nil && !isNil(o.TypeDisplay) {
		return true
	}

	return false
}

// SetTypeDisplay gets a reference to the given string and assigns it to the TypeDisplay field.
func (o *TerraformPackageUploadResponse) SetTypeDisplay(v string) {
	o.TypeDisplay = &v
}

// GetUploadedAt returns the UploadedAt field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetUploadedAt() time.Time {
	if o == nil || isNil(o.UploadedAt) {
		var ret time.Time
		return ret
	}
	return *o.UploadedAt
}

// GetUploadedAtOk returns a tuple with the UploadedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetUploadedAtOk() (*time.Time, bool) {
	if o == nil || isNil(o.UploadedAt) {
		return nil, false
	}
	return o.UploadedAt, true
}

// HasUploadedAt returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasUploadedAt() bool {
	if o != nil && !isNil(o.UploadedAt) {
		return true
	}

	return false
}

// SetUploadedAt gets a reference to the given time.Time and assigns it to the UploadedAt field.
func (o *TerraformPackageUploadResponse) SetUploadedAt(v time.Time) {
	o.UploadedAt = &v
}

// GetUploader returns the Uploader field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetUploader() string {
	if o == nil || isNil(o.Uploader) {
		var ret string
		return ret
	}
	return *o.Uploader
}

// GetUploaderOk returns a tuple with the Uploader field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetUploaderOk() (*string, bool) {
	if o == nil || isNil(o.Uploader) {
		return nil, false
	}
	return o.Uploader, true
}

// HasUploader returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasUploader() bool {
	if o != nil && !isNil(o.Uploader) {
		return true
	}

	return false
}

// SetUploader gets a reference to the given string and assigns it to the Uploader field.
func (o *TerraformPackageUploadResponse) SetUploader(v string) {
	o.Uploader = &v
}

// GetUploaderUrl returns the UploaderUrl field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetUploaderUrl() string {
	if o == nil || isNil(o.UploaderUrl) {
		var ret string
		return ret
	}
	return *o.UploaderUrl
}

// GetUploaderUrlOk returns a tuple with the UploaderUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetUploaderUrlOk() (*string, bool) {
	if o == nil || isNil(o.UploaderUrl) {
		return nil, false
	}
	return o.UploaderUrl, true
}

// HasUploaderUrl returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasUploaderUrl() bool {
	if o != nil && !isNil(o.UploaderUrl) {
		return true
	}

	return false
}

// SetUploaderUrl gets a reference to the given string and assigns it to the UploaderUrl field.
func (o *TerraformPackageUploadResponse) SetUploaderUrl(v string) {
	o.UploaderUrl = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetVersion() string {
	if o == nil || isNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetVersionOk() (*string, bool) {
	if o == nil || isNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasVersion() bool {
	if o != nil && !isNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *TerraformPackageUploadResponse) SetVersion(v string) {
	o.Version = &v
}

// GetVersionOrig returns the VersionOrig field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetVersionOrig() string {
	if o == nil || isNil(o.VersionOrig) {
		var ret string
		return ret
	}
	return *o.VersionOrig
}

// GetVersionOrigOk returns a tuple with the VersionOrig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetVersionOrigOk() (*string, bool) {
	if o == nil || isNil(o.VersionOrig) {
		return nil, false
	}
	return o.VersionOrig, true
}

// HasVersionOrig returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasVersionOrig() bool {
	if o != nil && !isNil(o.VersionOrig) {
		return true
	}

	return false
}

// SetVersionOrig gets a reference to the given string and assigns it to the VersionOrig field.
func (o *TerraformPackageUploadResponse) SetVersionOrig(v string) {
	o.VersionOrig = &v
}

// GetVulnerabilityScanResultsUrl returns the VulnerabilityScanResultsUrl field value if set, zero value otherwise.
func (o *TerraformPackageUploadResponse) GetVulnerabilityScanResultsUrl() string {
	if o == nil || isNil(o.VulnerabilityScanResultsUrl) {
		var ret string
		return ret
	}
	return *o.VulnerabilityScanResultsUrl
}

// GetVulnerabilityScanResultsUrlOk returns a tuple with the VulnerabilityScanResultsUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformPackageUploadResponse) GetVulnerabilityScanResultsUrlOk() (*string, bool) {
	if o == nil || isNil(o.VulnerabilityScanResultsUrl) {
		return nil, false
	}
	return o.VulnerabilityScanResultsUrl, true
}

// HasVulnerabilityScanResultsUrl returns a boolean if a field has been set.
func (o *TerraformPackageUploadResponse) HasVulnerabilityScanResultsUrl() bool {
	if o != nil && !isNil(o.VulnerabilityScanResultsUrl) {
		return true
	}

	return false
}

// SetVulnerabilityScanResultsUrl gets a reference to the given string and assigns it to the VulnerabilityScanResultsUrl field.
func (o *TerraformPackageUploadResponse) SetVulnerabilityScanResultsUrl(v string) {
	o.VulnerabilityScanResultsUrl = &v
}

func (o TerraformPackageUploadResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Architectures) {
		toSerialize["architectures"] = o.Architectures
	}
	if o.CdnUrl.IsSet() {
		toSerialize["cdn_url"] = o.CdnUrl.Get()
	}
	if !isNil(o.ChecksumMd5) {
		toSerialize["checksum_md5"] = o.ChecksumMd5
	}
	if !isNil(o.ChecksumSha1) {
		toSerialize["checksum_sha1"] = o.ChecksumSha1
	}
	if !isNil(o.ChecksumSha256) {
		toSerialize["checksum_sha256"] = o.ChecksumSha256
	}
	if !isNil(o.ChecksumSha512) {
		toSerialize["checksum_sha512"] = o.ChecksumSha512
	}
	if !isNil(o.DependenciesChecksumMd5) {
		toSerialize["dependencies_checksum_md5"] = o.DependenciesChecksumMd5
	}
	if !isNil(o.DependenciesUrl) {
		toSerialize["dependencies_url"] = o.DependenciesUrl
	}
	if !isNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if o.Distro.IsSet() {
		toSerialize["distro"] = o.Distro.Get()
	}
	if !isNil(o.DistroVersion) {
		toSerialize["distro_version"] = o.DistroVersion
	}
	if !isNil(o.Downloads) {
		toSerialize["downloads"] = o.Downloads
	}
	if !isNil(o.Epoch) {
		toSerialize["epoch"] = o.Epoch
	}
	if !isNil(o.Extension) {
		toSerialize["extension"] = o.Extension
	}
	if !isNil(o.Filename) {
		toSerialize["filename"] = o.Filename
	}
	if !isNil(o.Files) {
		toSerialize["files"] = o.Files
	}
	if !isNil(o.Format) {
		toSerialize["format"] = o.Format
	}
	if !isNil(o.FormatUrl) {
		toSerialize["format_url"] = o.FormatUrl
	}
	if !isNil(o.IdentifierPerm) {
		toSerialize["identifier_perm"] = o.IdentifierPerm
	}
	if !isNil(o.Indexed) {
		toSerialize["indexed"] = o.Indexed
	}
	if !isNil(o.IsDownloadable) {
		toSerialize["is_downloadable"] = o.IsDownloadable
	}
	if !isNil(o.IsQuarantined) {
		toSerialize["is_quarantined"] = o.IsQuarantined
	}
	if !isNil(o.IsSyncAwaiting) {
		toSerialize["is_sync_awaiting"] = o.IsSyncAwaiting
	}
	if !isNil(o.IsSyncCompleted) {
		toSerialize["is_sync_completed"] = o.IsSyncCompleted
	}
	if !isNil(o.IsSyncFailed) {
		toSerialize["is_sync_failed"] = o.IsSyncFailed
	}
	if !isNil(o.IsSyncInFlight) {
		toSerialize["is_sync_in_flight"] = o.IsSyncInFlight
	}
	if !isNil(o.IsSyncInProgress) {
		toSerialize["is_sync_in_progress"] = o.IsSyncInProgress
	}
	if !isNil(o.License) {
		toSerialize["license"] = o.License
	}
	if !isNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !isNil(o.Namespace) {
		toSerialize["namespace"] = o.Namespace
	}
	if !isNil(o.NamespaceUrl) {
		toSerialize["namespace_url"] = o.NamespaceUrl
	}
	if !isNil(o.NumFiles) {
		toSerialize["num_files"] = o.NumFiles
	}
	if !isNil(o.OriginRepository) {
		toSerialize["origin_repository"] = o.OriginRepository
	}
	if !isNil(o.OriginRepositoryUrl) {
		toSerialize["origin_repository_url"] = o.OriginRepositoryUrl
	}
	if !isNil(o.PackageType) {
		toSerialize["package_type"] = o.PackageType
	}
	if !isNil(o.Release) {
		toSerialize["release"] = o.Release
	}
	if !isNil(o.Repository) {
		toSerialize["repository"] = o.Repository
	}
	if !isNil(o.RepositoryUrl) {
		toSerialize["repository_url"] = o.RepositoryUrl
	}
	if !isNil(o.SecurityScanCompletedAt) {
		toSerialize["security_scan_completed_at"] = o.SecurityScanCompletedAt
	}
	if !isNil(o.SecurityScanStartedAt) {
		toSerialize["security_scan_started_at"] = o.SecurityScanStartedAt
	}
	if o.SecurityScanStatus.IsSet() {
		toSerialize["security_scan_status"] = o.SecurityScanStatus.Get()
	}
	if !isNil(o.SecurityScanStatusUpdatedAt) {
		toSerialize["security_scan_status_updated_at"] = o.SecurityScanStatusUpdatedAt
	}
	if !isNil(o.SelfHtmlUrl) {
		toSerialize["self_html_url"] = o.SelfHtmlUrl
	}
	if !isNil(o.SelfUrl) {
		toSerialize["self_url"] = o.SelfUrl
	}
	if o.SignatureUrl.IsSet() {
		toSerialize["signature_url"] = o.SignatureUrl.Get()
	}
	if !isNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	if !isNil(o.Slug) {
		toSerialize["slug"] = o.Slug
	}
	if !isNil(o.SlugPerm) {
		toSerialize["slug_perm"] = o.SlugPerm
	}
	if !isNil(o.Stage) {
		toSerialize["stage"] = o.Stage
	}
	if !isNil(o.StageStr) {
		toSerialize["stage_str"] = o.StageStr
	}
	if !isNil(o.StageUpdatedAt) {
		toSerialize["stage_updated_at"] = o.StageUpdatedAt
	}
	if !isNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !isNil(o.StatusReason) {
		toSerialize["status_reason"] = o.StatusReason
	}
	if !isNil(o.StatusStr) {
		toSerialize["status_str"] = o.StatusStr
	}
	if !isNil(o.StatusUpdatedAt) {
		toSerialize["status_updated_at"] = o.StatusUpdatedAt
	}
	if !isNil(o.StatusUrl) {
		toSerialize["status_url"] = o.StatusUrl
	}
	if !isNil(o.Subtype) {
		toSerialize["subtype"] = o.Subtype
	}
	if !isNil(o.Summary) {
		toSerialize["summary"] = o.Summary
	}
	if !isNil(o.SyncFinishedAt) {
		toSerialize["sync_finished_at"] = o.SyncFinishedAt
	}
	if !isNil(o.SyncProgress) {
		toSerialize["sync_progress"] = o.SyncProgress
	}
	if !isNil(o.TagsImmutable) {
		toSerialize["tags_immutable"] = o.TagsImmutable
	}
	if !isNil(o.TypeDisplay) {
		toSerialize["type_display"] = o.TypeDisplay
	}
	if !isNil(o.UploadedAt) {
		toSerialize["uploaded_at"] = o.UploadedAt
	}
	if !isNil(o.Uploader) {
		toSerialize["uploader"] = o.Uploader
	}
	if !isNil(o.UploaderUrl) {
		toSerialize["uploader_url"] = o.UploaderUrl
	}
	if !isNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !isNil(o.VersionOrig) {
		toSerialize["version_orig"] = o.VersionOrig
	}
	if !isNil(o.VulnerabilityScanResultsUrl) {
		toSerialize["vulnerability_scan_results_url"] = o.VulnerabilityScanResultsUrl
	}
	return json.Marshal(toSerialize)
}

type NullableTerraformPackageUploadResponse struct {
	value *TerraformPackageUploadResponse
	isSet bool
}

func (v NullableTerraformPackageUploadResponse) Get() *TerraformPackageUploadResponse {
	return v.value
}

func (v *NullableTerraformPackageUploadResponse) Set(val *TerraformPackageUploadResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTerraformPackageUploadResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTerraformPackageUploadResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTerraformPackageUploadResponse(val *TerraformPackageUploadResponse) *NullableTerraformPackageUploadResponse {
	return &NullableTerraformPackageUploadResponse{value: val, isSet: true}
}

func (v NullableTerraformPackageUploadResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTerraformPackageUploadResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
