/*
Cloudsmith API

The API to the Cloudsmith Service

API version: 1.121.3
Contact: support@cloudsmith.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudsmith

import (
	"encoding/json"
)

// PackagesQuarantine struct for PackagesQuarantine
type PackagesQuarantine struct {
	// If true, the package be restored from quarantine.
	Restore *bool `json:"restore,omitempty"`
}

// NewPackagesQuarantine instantiates a new PackagesQuarantine object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPackagesQuarantine() *PackagesQuarantine {
	this := PackagesQuarantine{}
	return &this
}

// NewPackagesQuarantineWithDefaults instantiates a new PackagesQuarantine object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPackagesQuarantineWithDefaults() *PackagesQuarantine {
	this := PackagesQuarantine{}
	return &this
}

// GetRestore returns the Restore field value if set, zero value otherwise.
func (o *PackagesQuarantine) GetRestore() bool {
	if o == nil || o.Restore == nil {
		var ret bool
		return ret
	}
	return *o.Restore
}

// GetRestoreOk returns a tuple with the Restore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PackagesQuarantine) GetRestoreOk() (*bool, bool) {
	if o == nil || o.Restore == nil {
		return nil, false
	}
	return o.Restore, true
}

// HasRestore returns a boolean if a field has been set.
func (o *PackagesQuarantine) HasRestore() bool {
	if o != nil && o.Restore != nil {
		return true
	}

	return false
}

// SetRestore gets a reference to the given bool and assigns it to the Restore field.
func (o *PackagesQuarantine) SetRestore(v bool) {
	o.Restore = &v
}

func (o PackagesQuarantine) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Restore != nil {
		toSerialize["restore"] = o.Restore
	}
	return json.Marshal(toSerialize)
}

type NullablePackagesQuarantine struct {
	value *PackagesQuarantine
	isSet bool
}

func (v NullablePackagesQuarantine) Get() *PackagesQuarantine {
	return v.value
}

func (v *NullablePackagesQuarantine) Set(val *PackagesQuarantine) {
	v.value = val
	v.isSet = true
}

func (v NullablePackagesQuarantine) IsSet() bool {
	return v.isSet
}

func (v *NullablePackagesQuarantine) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePackagesQuarantine(val *PackagesQuarantine) *NullablePackagesQuarantine {
	return &NullablePackagesQuarantine{value: val, isSet: true}
}

func (v NullablePackagesQuarantine) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePackagesQuarantine) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
