/*
Cloudsmith API (v1)

The API to the Cloudsmith Service

API version: 1.181.6
Contact: support@cloudsmith.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudsmith

import (
	"encoding/json"
)

// UserBriefResponse struct for UserBriefResponse
type UserBriefResponse struct {
	// If true then you're logged in as a user.
	Authenticated *bool `json:"authenticated,omitempty"`
	// Your email address that we use to contact you. This is only visible to you.
	Email NullableString `json:"email,omitempty"`
	// The full name of the user (if any).
	Name NullableString `json:"name,omitempty"`
	// The URL for the full profile of the user.
	ProfileUrl NullableString `json:"profile_url,omitempty"`
	SelfUrl    *string        `json:"self_url,omitempty"`
	Slug       NullableString `json:"slug,omitempty"`
	SlugPerm   NullableString `json:"slug_perm,omitempty"`
}

// NewUserBriefResponse instantiates a new UserBriefResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserBriefResponse() *UserBriefResponse {
	this := UserBriefResponse{}
	return &this
}

// NewUserBriefResponseWithDefaults instantiates a new UserBriefResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserBriefResponseWithDefaults() *UserBriefResponse {
	this := UserBriefResponse{}
	return &this
}

// GetAuthenticated returns the Authenticated field value if set, zero value otherwise.
func (o *UserBriefResponse) GetAuthenticated() bool {
	if o == nil || isNil(o.Authenticated) {
		var ret bool
		return ret
	}
	return *o.Authenticated
}

// GetAuthenticatedOk returns a tuple with the Authenticated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserBriefResponse) GetAuthenticatedOk() (*bool, bool) {
	if o == nil || isNil(o.Authenticated) {
		return nil, false
	}
	return o.Authenticated, true
}

// HasAuthenticated returns a boolean if a field has been set.
func (o *UserBriefResponse) HasAuthenticated() bool {
	if o != nil && !isNil(o.Authenticated) {
		return true
	}

	return false
}

// SetAuthenticated gets a reference to the given bool and assigns it to the Authenticated field.
func (o *UserBriefResponse) SetAuthenticated(v bool) {
	o.Authenticated = &v
}

// GetEmail returns the Email field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserBriefResponse) GetEmail() string {
	if o == nil || isNil(o.Email.Get()) {
		var ret string
		return ret
	}
	return *o.Email.Get()
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserBriefResponse) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Email.Get(), o.Email.IsSet()
}

// HasEmail returns a boolean if a field has been set.
func (o *UserBriefResponse) HasEmail() bool {
	if o != nil && o.Email.IsSet() {
		return true
	}

	return false
}

// SetEmail gets a reference to the given NullableString and assigns it to the Email field.
func (o *UserBriefResponse) SetEmail(v string) {
	o.Email.Set(&v)
}

// SetEmailNil sets the value for Email to be an explicit nil
func (o *UserBriefResponse) SetEmailNil() {
	o.Email.Set(nil)
}

// UnsetEmail ensures that no value is present for Email, not even an explicit nil
func (o *UserBriefResponse) UnsetEmail() {
	o.Email.Unset()
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserBriefResponse) GetName() string {
	if o == nil || isNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserBriefResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *UserBriefResponse) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *UserBriefResponse) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *UserBriefResponse) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *UserBriefResponse) UnsetName() {
	o.Name.Unset()
}

// GetProfileUrl returns the ProfileUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserBriefResponse) GetProfileUrl() string {
	if o == nil || isNil(o.ProfileUrl.Get()) {
		var ret string
		return ret
	}
	return *o.ProfileUrl.Get()
}

// GetProfileUrlOk returns a tuple with the ProfileUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserBriefResponse) GetProfileUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProfileUrl.Get(), o.ProfileUrl.IsSet()
}

// HasProfileUrl returns a boolean if a field has been set.
func (o *UserBriefResponse) HasProfileUrl() bool {
	if o != nil && o.ProfileUrl.IsSet() {
		return true
	}

	return false
}

// SetProfileUrl gets a reference to the given NullableString and assigns it to the ProfileUrl field.
func (o *UserBriefResponse) SetProfileUrl(v string) {
	o.ProfileUrl.Set(&v)
}

// SetProfileUrlNil sets the value for ProfileUrl to be an explicit nil
func (o *UserBriefResponse) SetProfileUrlNil() {
	o.ProfileUrl.Set(nil)
}

// UnsetProfileUrl ensures that no value is present for ProfileUrl, not even an explicit nil
func (o *UserBriefResponse) UnsetProfileUrl() {
	o.ProfileUrl.Unset()
}

// GetSelfUrl returns the SelfUrl field value if set, zero value otherwise.
func (o *UserBriefResponse) GetSelfUrl() string {
	if o == nil || isNil(o.SelfUrl) {
		var ret string
		return ret
	}
	return *o.SelfUrl
}

// GetSelfUrlOk returns a tuple with the SelfUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserBriefResponse) GetSelfUrlOk() (*string, bool) {
	if o == nil || isNil(o.SelfUrl) {
		return nil, false
	}
	return o.SelfUrl, true
}

// HasSelfUrl returns a boolean if a field has been set.
func (o *UserBriefResponse) HasSelfUrl() bool {
	if o != nil && !isNil(o.SelfUrl) {
		return true
	}

	return false
}

// SetSelfUrl gets a reference to the given string and assigns it to the SelfUrl field.
func (o *UserBriefResponse) SetSelfUrl(v string) {
	o.SelfUrl = &v
}

// GetSlug returns the Slug field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserBriefResponse) GetSlug() string {
	if o == nil || isNil(o.Slug.Get()) {
		var ret string
		return ret
	}
	return *o.Slug.Get()
}

// GetSlugOk returns a tuple with the Slug field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserBriefResponse) GetSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Slug.Get(), o.Slug.IsSet()
}

// HasSlug returns a boolean if a field has been set.
func (o *UserBriefResponse) HasSlug() bool {
	if o != nil && o.Slug.IsSet() {
		return true
	}

	return false
}

// SetSlug gets a reference to the given NullableString and assigns it to the Slug field.
func (o *UserBriefResponse) SetSlug(v string) {
	o.Slug.Set(&v)
}

// SetSlugNil sets the value for Slug to be an explicit nil
func (o *UserBriefResponse) SetSlugNil() {
	o.Slug.Set(nil)
}

// UnsetSlug ensures that no value is present for Slug, not even an explicit nil
func (o *UserBriefResponse) UnsetSlug() {
	o.Slug.Unset()
}

// GetSlugPerm returns the SlugPerm field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserBriefResponse) GetSlugPerm() string {
	if o == nil || isNil(o.SlugPerm.Get()) {
		var ret string
		return ret
	}
	return *o.SlugPerm.Get()
}

// GetSlugPermOk returns a tuple with the SlugPerm field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserBriefResponse) GetSlugPermOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SlugPerm.Get(), o.SlugPerm.IsSet()
}

// HasSlugPerm returns a boolean if a field has been set.
func (o *UserBriefResponse) HasSlugPerm() bool {
	if o != nil && o.SlugPerm.IsSet() {
		return true
	}

	return false
}

// SetSlugPerm gets a reference to the given NullableString and assigns it to the SlugPerm field.
func (o *UserBriefResponse) SetSlugPerm(v string) {
	o.SlugPerm.Set(&v)
}

// SetSlugPermNil sets the value for SlugPerm to be an explicit nil
func (o *UserBriefResponse) SetSlugPermNil() {
	o.SlugPerm.Set(nil)
}

// UnsetSlugPerm ensures that no value is present for SlugPerm, not even an explicit nil
func (o *UserBriefResponse) UnsetSlugPerm() {
	o.SlugPerm.Unset()
}

func (o UserBriefResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Authenticated) {
		toSerialize["authenticated"] = o.Authenticated
	}
	if o.Email.IsSet() {
		toSerialize["email"] = o.Email.Get()
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.ProfileUrl.IsSet() {
		toSerialize["profile_url"] = o.ProfileUrl.Get()
	}
	if !isNil(o.SelfUrl) {
		toSerialize["self_url"] = o.SelfUrl
	}
	if o.Slug.IsSet() {
		toSerialize["slug"] = o.Slug.Get()
	}
	if o.SlugPerm.IsSet() {
		toSerialize["slug_perm"] = o.SlugPerm.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableUserBriefResponse struct {
	value *UserBriefResponse
	isSet bool
}

func (v NullableUserBriefResponse) Get() *UserBriefResponse {
	return v.value
}

func (v *NullableUserBriefResponse) Set(val *UserBriefResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUserBriefResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUserBriefResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserBriefResponse(val *UserBriefResponse) *NullableUserBriefResponse {
	return &NullableUserBriefResponse{value: val, isSet: true}
}

func (v NullableUserBriefResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserBriefResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
